CREATE TABLE IF NOT EXISTS `USER_ORDER` (
  `PK_ORDER_ID` BIGINT NOT NULL,
  `FK_USER_ID` BIGINT NULL,
  `PERSON_ID` BIGINT NULL,
  `DETAIL` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_ORDER_ID`),
  INDEX `USER_ID` (`FK_USER_ID`)
  );
